import {
  ArrowRight,
  ArrowUpRight,
  Check,
  CircleAlert,
  Command,
  Copy,
  CornerDownLeft,
  Lock,
  LockOpen,
  Menu,
  Moon,
  Quote,
  Search,
  Sun,
  Sunset,
  X,
  Ban,
  CodeXml,
  Disc3,
  FlaskConical,
  Footprints,
  GitMerge,
  GraduationCap,
  Mountain,
  Presentation,
  Repeat,
  UserRound,
  CalendarRange,
  UsersRound,
  Handshake,
  PenTool,
  Plane,
  Sparkles,
  SquareDashed,
  ToyBrick,
  WandSparkles,
} from "lucide-react";
import type { IconTokens } from "../contract";

export const icons = {
  set: {
    "arrow-right": ArrowRight,
    "arrow-up-right": ArrowUpRight,
    sun: Sun,
    sunset: Sunset,
    moon: Moon,
    lock: Lock,
    "lock-open": LockOpen,
    "circle-alert": CircleAlert,
    menu: Menu,
    x: X,
    copy: Copy,
    check: Check,
    search: Search,
    command: Command,
    quote: Quote,
    "corner-down-left": CornerDownLeft,
    "toy-brick": ToyBrick,
    sparkles: Sparkles,
    "square-dashed": SquareDashed,
    ban: Ban,
    "wand-sparkles": WandSparkles,
    "code-xml": CodeXml,
    "flask-conical": FlaskConical,
    "git-merge": GitMerge,
    mountain: Mountain,
    footprints: Footprints,
    "disc-3": Disc3,
    "graduation-cap": GraduationCap,
    presentation: Presentation,
    repeat: Repeat,
    "user-round": UserRound,
    "calendar-range": CalendarRange,
    "users-round": UsersRound,
    handshake: Handshake,
    "pen-tool": PenTool,
    plane: Plane,
  },
  strokeWidth: 1.5,
  size: { ui: 18, nav: 20 },
} satisfies IconTokens;
