export const contentExplorer = {
  slug: "content-explorer",
  title: "Content Explorer",
  company: "Miro",
  year: 2026,
  access: "protected",
  bottomLine:
    "Admins could manage users and teams, but not content: support handled about 2,000 bulk-change requests a quarter. I designed Content Explorer; 480 admins used it in the first public-beta week.",
  role: "Lead and only designer",
  team: "1 PM, engineering lead, the Content Lifecycle team",
  timeline: "GA Sep 2026",
  partners: "Designed alongside Content Lifecycle, bulk actions and analytics, with the PM, the engineering lead and the design-system team.",
  scope: ["Information architecture", "Permission model", "Prototyping"],
  metrics: [
    { value: "46", label: "organisations asked for the private beta", context: "one of the most demanded admin capabilities" },
    { value: "480", label: "admins in the first public-beta week", context: "across more than 100 enterprises" },
    { value: "15", label: "of 22 pilot organisations came back", context: "on four or more days out of 50" },
  ],
  beats: [
    {
      label: "Frame",
      text: "Admins managed users and teams, but not boards. Support handled about 2,000 bulk-change requests a quarter, and some organisations hold 80,000 boards.",
    },
    {
      label: "Shape",
      text: "I named the states admins think in: Available, In trash, Retained. A role-based admin model and a full-stack prototype settled scope before engineering started.",
    },
    {
      label: "Ship",
      text: "Private beta in July, public beta in August, GA in September. Content Lifecycle and bulk actions now build on the same table.",
    },
  ],
  artifacts: [
    {
      kind: "screenshot",
      src: "/media/protected/content-explorer/available.png",
      ratio: "16/10",
      alt: "The Available view of Content Explorer: every board in the organisation in one table with filters.",
      caption: "The Available view: every board in the organisation, in one table.",
    },
    {
      kind: "diagram",
      layers: ["Content Admin", "Sensitive Content Admin", "Lifecycle Admin"],
      alt: "The admin roles, from Content Admin up to Sensitive Content Admin and Lifecycle Admin.",
      caption: "Granular admin roles, so each view opens only for the right people.",
    },
    {
      kind: "screenshot",
      src: "/media/protected/content-explorer/filtered.png",
      ratio: "16/10",
      alt: "Content Explorer filtered by classification with FilterPill, two boards left.",
      caption: "FilterPill, merged into Miro's design system after three teams hand-rolled it.",
    },
  ],
  askMeAbout: [
    "Why the boards are Available, not active",
    "Keeping a table usable at 80,000 boards",
    "Shipping two production PRs as a designer",
  ],
  cover: {
    kind: "video",
    src: "/projects/content-explorer/loop.mp4",
    poster: "/projects/content-explorer/loop.jpg",
    ratio: "16/10",
    alt: "Content Explorer in the admin console: filtering boards by classification, then the Data Discovery and Content Lifecycle views.",
  },
  story: [
    {
      id: "why",
      nav: "Why we started",
      title: "Admins could manage users and teams, but not content",
      lead: "Support handled about 2,000 bulk-change requests a quarter, because administrators had no way to make those changes themselves. Some organisations hold 80,000 boards.",
    },
    {
      id: "naming",
      nav: "Naming",
      title: "Name the states admins already think in",
      steps: [
        {
          id: "available",
          nav: "Available, not active",
          title: "Boards are Available, not active",
          text: "The names come from content lifecycle stages: Available, In trash, Retained. When the launch announcement said active, I argued for the lifecycle word, and the PM corrected the copy. The terms I set are what customers read today.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/content-explorer/available.png",
            ratio: "16/10",
            alt: "The Available view of Content Explorer: every board in the organisation in one table with filters.",
            caption: "The Available view: every board in the organisation, in one table.",
          },
        },
        {
          id: "views",
          nav: "Four views",
          title: "Four views, one table pattern",
          text: "Available, Trash, Data Discovery and Content Lifecycle share one table, one filter row and one board-details drawer with sharing, permissions and lifecycle context.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/content-explorer/drawer.png",
            ratio: "16/10",
            alt: "The board-details drawer open over the table: owner, classification and sharing.",
            caption: "The board-details drawer: owner, classification and sharing in one place.",
          },
        },
        {
          id: "roles",
          nav: "Admin roles",
          title: "Each view opens only for the right people",
          text: "A granular admin model: Content Admin, Sensitive Content Admin and Data Governance Admin, with sensitive discovery and lifecycle views behind the stronger roles. I designed the roles and the access flows around them.",
          artifact: {
            kind: "diagram",
            layers: ["Content Admin", "Sensitive Content Admin", "Lifecycle Admin"],
            alt: "The admin roles, from Content Admin up to Sensitive Content Admin and Lifecycle Admin.",
            caption: "Granular admin roles, so each view opens only for the right people.",
          },
        },
      ],
    },
    {
      id: "prototype",
      nav: "Prototype first",
      title: "Settle scope in a working model, not in a debate",
      steps: [
        {
          id: "model",
          nav: "Working model",
          title: "A full-stack model of the admin console",
          text: "I treat prototypes as executable specs. A 93,000-line working model, with 2,038 of its 3,450 commits mine, settled bulk actions, board moves and lifecycle scope before engineering started.",
        },
        {
          id: "filter-pill",
          nav: "FilterPill",
          title: "One filter pill instead of three",
          text: "Three teams had hand-rolled the same filter pill. I wrote the proposal from a working implementation, then built FilterPill into Miro's design system myself: 1,660 lines of component, specs, stories, tests and docs.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/content-explorer/filtered.png",
            ratio: "16/10",
            alt: "Content Explorer filtered by classification with FilterPill, two boards left.",
            caption: "FilterPill at work: the dimension at rest, its values once set.",
          },
        },
        {
          id: "production",
          nav: "Production code",
          title: "Closing the gap in code, not in a redline",
          text: "Two merged pull requests in Miro's production client: limited-access indicators across Data Discovery, and the end-user Trash page rebuilt on the shared virtual table, deleting the legacy one.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/content-explorer/discovery.png",
            ratio: "16/10",
            alt: "Data Discovery: boards with sensitive content, with limited-access boards marked in the table.",
            caption: "Data Discovery, with limited-access boards marked in the table.",
          },
        },
      ],
    },
    {
      id: "results",
      nav: "Results",
      title: "480 admins in the first public-beta week",
      lead: "Kick-off in August 2025, private beta in July 2026, public beta in August and general availability in September. 46 organisations asked for the private beta, one of the most demanded admin capabilities.",
      steps: [
        {
          id: "pilot",
          nav: "Pilot",
          title: "Admins worked in it, not just glanced",
          text: "15 of 22 active pilot organisations came back on four or more separate days in a 50-day window, 8 of them on twelve or more. The lifecycle view reached 3 of the 4 eligible organisations.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/content-explorer/lifecycle.png",
            ratio: "16/10",
            alt: "The Content Lifecycle view: state, retention and disposition dates for every board.",
            caption: "Content Lifecycle: state, retention and disposition for every board.",
          },
        },
        {
          id: "next",
          nav: "What's next",
          title: "Bulk actions on the same table",
          text: "Bulk trash, restore and permanent delete went to private beta in September 2026 for the same cohort, built to take over those 2,000 manual requests a quarter.",
        },
      ],
    },
  ],
} as const;
