export const miroAnalytics = {
  slug: "miro-analytics",
  title: "Miro Analytics",
  company: "Miro",
  year: 2024,
  access: "protected",
  bottomLine:
    "Insights was the least opened page in Miro: five widgets, untouched for four years. We rebuilt analytics for Enterprise admins, and it now draws over 1,000 visits a week.",
  role: "Product designer, end to end",
  team: "1 PM, 3 designers, 2 dev teams",
  timeline: "Since 2024",
  partners: "Worked with the CEO, the CPO, Customer Success and two development teams.",
  scope: ["Research", "Workshops", "Prototyping"],
  metrics: [
    { value: "1,000", unit: "+", label: "visits every week", context: "after launch to all Enterprise admins" },
    { value: "4", unit: "/5", label: "average satisfaction", context: "in-product poll across 30 organisations" },
    { value: "150", label: "Salesforce requests for data visibility", context: "the signal we started from" },
  ],
  beats: [
    {
      label: "Frame",
      text: "Insights had five widgets and no code change in four years, while 150 Salesforce requests asked for more data. Admins stopped trusting what they saw.",
    },
    {
      label: "Shape",
      text: "Strong internal pushback met us, so I led with research: 150 requests, 12 interviews, product data. The plan: trustworthy data first, actionability next, then AI.",
    },
    {
      label: "Ship",
      text: "Launched to all Enterprise admins: 1,000+ visits a week, 4 out of 5 satisfaction. Since then I designed use-case and AI analytics, gated by role.",
    },
  ],
  artifacts: [
    {
      kind: "compare",
      before: { src: "/media/protected/miro-analytics/small-before.png", alt: "The old Insights users chart: one bar per month, active users only." },
      after: { src: "/media/protected/miro-analytics/small-after.png", alt: "The new user history: total and active users with a role filter and a period pager." },
      ratio: "540/300",
      caption: "It started small: the old users chart, then the new user history.",
    },
    {
      kind: "screenshot",
      src: "/media/protected/miro-analytics/layers.png",
      ratio: "1006/520",
      alt: "Layers of success: trustworthy data set, API access, insights dashboard, Content Explorer and report center.",
      caption: "Everything starts with data. Every other layer works on top of it.",
    },
    {
      kind: "screenshot",
      src: "/media/protected/miro-analytics/design-language.png",
      ratio: "1300/506",
      alt: "The chart design language next to the Figma plugin that generates charts from it.",
      caption: "Shared chart components, and the Figma plugin that generates charts from them.",
    },
  ],
  askMeAbout: [
    "How research turned strong internal pushback into support",
    "Why trustworthy data came before any new chart",
    "Why Company Admins see the numbers but not the boards",
  ],
  cover: {
    kind: "video",
    src: "/projects/miro-analytics/loop.mp4",
    poster: "/projects/miro-analytics/loop.jpg",
    ratio: "16/10",
    alt: "Miro Analytics in the admin console: the Miro AI tab, then the Teams using AI drill-down.",
  },
  story: [
    {
      id: "why",
      nav: "Why we started",
      title: "Insights was the least opened page in Miro",
      lead: "The whole analytics offer for Enterprise was five widgets, and nobody had changed their code in four years. Meanwhile, 150 requests in Salesforce asked for more data visibility.",
    },
    {
      id: "research",
      nav: "Finding out",
      title: "What should admins get from their data?",
      quote: "How can analysing Miro usage data help admins streamline daily tasks and boost overall adoption?",
      lead: "I looked at it from three sides at once: 150 Salesforce requests, 12 in-depth interviews and product data analysis.",
      steps: [
        {
          id: "jobs",
          nav: "Admin jobs",
          title: "Three jobs every admin has",
          text: "We mapped what admins do, the data they need from Miro and what they act on. It came down to three jobs: manage Miro at scale, drive the adoption of Miro, and monitor its security and compliance.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/research-board.png",
            ratio: "677/476",
            alt: "Research board with three columns: manage Miro at scale, drive adoption, monitor security and compliance.",
            caption: "Jobs to be done, data needs and actions, for each admin job.",
          },
        },
        {
          id: "workflow",
          nav: "The workflow",
          title: "Understand, analyse, get a recommendation, act",
          text: "The admin workflow turned out to be extremely simple. Analytics is the gate to more advanced optimisation, but it needs many parts, and we had none of them.",
          points: [
            "No trustworthy data set, and no API to consume it",
            "No robust analytics dashboard",
            "No way to act on the content behind a widget",
            "No export for book-keeping, and no design language for charts",
          ],
        },
      ],
    },
    {
      id: "pushback",
      nav: "Pushback",
      title: "Nobody wanted to show admins the data",
      lead: "Stakeholders didn't want to invest in analytics. They were scared that exposing the data could lead to churn.",
      quote: "How might we prove the value of Miro?",
      steps: [
        {
          id: "arguments",
          nav: "Research as argument",
          title: "The research did the convincing",
          text: "Salesforce analysis showed customer satisfaction would grow with analytic tools. Interviews confirmed admins need analytics to drive wall-to-wall adoption. And we changed how we saw the admin: not an enemy cutting IT spend, but an ally who wants tools that bring the organisation value.",
        },
        {
          id: "layers",
          nav: "Layers of success",
          title: "Every layer of the ideal solution",
          text: "With the team I described every layer the ideal solution needs and how they work together: a trustworthy data set at the bottom, then API access and the insights dashboard, with Content Explorer and a report center on top.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/layers.png",
            ratio: "1006/520",
            alt: "Layers of success: trustworthy data set, API access, insights dashboard, Content Explorer and report center.",
            caption: "Layers of success, from a trustworthy data set up to a report center.",
          },
        },
      ],
    },
    {
      id: "build",
      nav: "Building it",
      title: "A solid foundation first, then make it act",
      lead: "Four rules for execution: start with a solid foundation, support actionability as soon as possible, aim to prove the value of Miro, and have a long-term plan.",
      steps: [
        {
          id: "small",
          nav: "Started small",
          title: "It started super small",
          text: "The first release replaced a lonely bar chart of users with a user history admins can trust: total and active users, a role filter and a period pager.",
          artifact: {
            kind: "compare",
            before: { src: "/media/protected/miro-analytics/small-before.png", alt: "The old Insights users chart: one bar per month, active users only." },
            after: { src: "/media/protected/miro-analytics/small-after.png", alt: "The new user history: total and active users with a role filter and a period pager." },
            ratio: "540/300",
            caption: "Before and after: the old users chart, then the new user history.",
          },
        },
        {
          id: "chart-language",
          nav: "Chart language",
          title: "A design language for charts",
          text: "We had no design language for data visualisation. I looked for every place that needs charts beyond analytics: the portfolio management tool, charts on the canvas, internal tools. With design stakeholders from those areas we landed on one set of shareable components, and a Figma plugin I built generates charts from them.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/design-language.png",
            ratio: "1300/506",
            alt: "The chart design language next to the Figma plugin that generates charts from it.",
            caption: "Shared chart components, and the Figma plugin that generates charts from them.",
          },
        },
        {
          id: "actionability",
          nav: "Actionability",
          title: "From numbers to something to do",
          text: "Next came content analytics with actionability: boards by state, classification and sharing. I vibe-coded it as a medium-fidelity prototype in Replit, then grew the next ideas in stages, skateboard, bike, Ferrari, with one colour-blind-safe palette across admin surfaces.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/actionability.png",
            ratio: "1024/568",
            alt: "Content analytics prototype: boards by state, board classification, board sharing and formats.",
            caption: "Content analytics with actionability, a medium-fidelity prototype vibe-coded in Replit.",
          },
        },
        {
          id: "miro-ai",
          nav: "Miro AI",
          title: "Down to every team and every user",
          text: "The Miro AI tab shows what people create with AI, which AI actions they use, and which teams and people use it at all. Every number opens a drill-down per team or per user, and the AI credits widgets show where the credits go.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/drill-down.png",
            ratio: "16/10",
            alt: "The Teams using AI drill-down: adoption and AI actions for every team, with search and export.",
            caption: "Teams using AI: the drill-down behind a single number.",
          },
        },
      ],
    },
    {
      id: "results",
      nav: "Results",
      title: "Over 1,000 visits every week",
      lead: "The new analytics launched to all Enterprise admins and will soon appear in other plans. Average satisfaction is 4 out of 5, from an in-product poll across 30 organisations. And we keep going: the backlog is full of improvements and new content.",
      steps: [
        {
          id: "use-cases",
          nav: "What's next",
          title: "Use cases, without leaking a single board",
          text: "I designed use-case analytics: a taxonomy widget on the analytics home with a drill-down into example boards. At the September 2026 permissions review, two rules came out of my argument: Company Admins see aggregate numbers, and board-level views need at least Content Admin.",
          artifact: {
            kind: "screenshot",
            src: "/media/protected/miro-analytics/use-cases.png",
            ratio: "16/10",
            alt: "Use-case analytics: shares per use-case category and their history by quarter.",
            caption: "Use-case analytics, designed and scoped with engineering, not shipped yet.",
          },
        },
        {
          id: "lessons",
          nav: "What I learned",
          title: "What I took from it",
          text: "Three notes I wrote down at the end of the project.",
          points: [
            "It's possible to change org culture and mindset if you have solid arguments.",
            "Always partner with your key users. They are your allies.",
            "Automation and vibe coding are making design better.",
          ],
        },
      ],
    },
  ],
} as const;
